import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FileText, Calendar } from "lucide-react";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navigation />

      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-primary via-primary/90 to-primary/80 text-primary-foreground py-16 md:py-20">
        <div className="absolute inset-0 bg-[url('data:image/svg+xml,%3Csvg width=%2260%22 height=%2260%22 viewBox=%220 0 60 60%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cg fill=%22none%22 fill-rule=%22evenodd%22%3E%3Cg fill=%22%23ffffff%22 fill-opacity=%220.05%22%3E%3Cpath d=%22M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z%22/%3E%3C/g%3E%3C/g%3E%3C/svg%3E')] opacity-30"></div>
        <div className="container mx-auto px-4 relative z-10">
          <div className="max-w-3xl mx-auto text-center">
            <Badge className="bg-accent text-accent-foreground mb-4">
              <FileText className="w-3 h-3 mr-1" />
              Legal
            </Badge>
            <h1 className="text-3xl md:text-5xl font-bold mb-4">
              Terms of Service
            </h1>
            <p className="text-lg text-primary-foreground/80 flex items-center justify-center gap-2">
              <Calendar className="w-4 h-4" />
              Last updated: December 5, 2024
            </p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-12 md:py-16">
        <div className="container mx-auto px-4">
          <Card className="max-w-4xl mx-auto">
            <CardContent className="p-8 md:p-12 prose prose-slate max-w-none">
              <h2 className="text-2xl font-bold text-primary mb-4">1. Agreement to Terms</h2>
              <p className="text-muted-foreground mb-6">
                By accessing or using High Spirit Grant Assistant, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground mb-6">
                High Spirit Grant Assistant is a platform that helps small business owners discover grant opportunities, receive AI-powered application coaching, and track their grant applications. We provide tools and information to assist with grant applications but do not guarantee funding approval.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">3. User Accounts</h2>
              <p className="text-muted-foreground mb-4">To use certain features, you must create an account. You agree to:</p>
              <ul className="list-disc list-inside text-muted-foreground mb-6 space-y-2">
                <li>Provide accurate and complete information</li>
                <li>Maintain the security of your account credentials</li>
                <li>Notify us immediately of any unauthorized access</li>
                <li>Be responsible for all activities under your account</li>
              </ul>

              <h2 className="text-2xl font-bold text-primary mb-4">4. Acceptable Use</h2>
              <p className="text-muted-foreground mb-4">You agree not to:</p>
              <ul className="list-disc list-inside text-muted-foreground mb-6 space-y-2">
                <li>Use the platform for any unlawful purpose</li>
                <li>Submit false or misleading information</li>
                <li>Attempt to gain unauthorized access to our systems</li>
                <li>Interfere with the proper functioning of the platform</li>
                <li>Use automated systems to access the platform without permission</li>
                <li>Impersonate any person or entity</li>
              </ul>

              <h2 className="text-2xl font-bold text-primary mb-4">5. AI Coaching Services</h2>
              <p className="text-muted-foreground mb-6">
                Our AI coaching features provide suggestions and assistance for grant applications. These suggestions are generated by artificial intelligence and should be reviewed and customized by you. We do not guarantee the accuracy, completeness, or effectiveness of AI-generated content. You are solely responsible for the content you submit in grant applications.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">6. Grant Information</h2>
              <p className="text-muted-foreground mb-6">
                We strive to provide accurate grant information but cannot guarantee the accuracy, completeness, or timeliness of all grant listings. Grant availability, deadlines, and requirements are determined by the respective funding organizations. Always verify information directly with the grant provider before applying.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">7. Intellectual Property</h2>
              <p className="text-muted-foreground mb-6">
                The High Spirit platform, including its design, features, and content (excluding user-generated content), is owned by us and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without our written permission.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">8. User Content</h2>
              <p className="text-muted-foreground mb-6">
                You retain ownership of content you create on our platform. By using our services, you grant us a limited license to store, process, and display your content as necessary to provide our services. We will not share your application content with third parties except as described in our Privacy Policy.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">9. Disclaimer of Warranties</h2>
              <p className="text-muted-foreground mb-6">
                The platform is provided "as is" without warranties of any kind. We do not guarantee that the platform will be uninterrupted, error-free, or that any defects will be corrected. We make no warranties regarding grant approval or funding success.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">10. Limitation of Liability</h2>
              <p className="text-muted-foreground mb-6">
                To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the platform, including but not limited to loss of profits, data, or business opportunities.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">11. Indemnification</h2>
              <p className="text-muted-foreground mb-6">
                You agree to indemnify and hold harmless High Spirit and its officers, directors, employees, and agents from any claims, damages, or expenses arising from your use of the platform or violation of these terms.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">12. Termination</h2>
              <p className="text-muted-foreground mb-6">
                We may terminate or suspend your account at any time for violation of these terms or for any other reason at our discretion. You may also terminate your account at any time by contacting us.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">13. Changes to Terms</h2>
              <p className="text-muted-foreground mb-6">
                We reserve the right to modify these terms at any time. We will notify you of significant changes via email or through the platform. Continued use after changes constitutes acceptance of the new terms.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">14. Governing Law</h2>
              <p className="text-muted-foreground mb-6">
                These terms shall be governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.
              </p>

              <h2 className="text-2xl font-bold text-primary mb-4">15. Contact Information</h2>
              <p className="text-muted-foreground">
                For questions about these Terms of Service, please contact us at{" "}
                <a href="mailto:legal@highspirit.com" className="text-accent hover:underline">
                  legal@highspirit.com
                </a>
                {" "}or through our{" "}
                <a href="/contact" className="text-accent hover:underline">
                  Contact page
                </a>.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default TermsOfService;